import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQueryProvider from "../common/providers/ReactQueryProvider";
import { ThemeProvider, useTheme } from "../common/providers/ThemeProvider";
import ThemeToggleButton from "@/common/components/SharedComponents/ThemeToggleButton";
import { SidebarProvider } from "@/common/components/SharedComponents/SideBarNavegation/delivery/components/sideBarContext";
import LayoutWithSidebar from "./layoutSideBar";
import PageTransitionWrapper from "@/common/components/SharedComponents/TransitionNavegation";
import 'antd/dist/reset.css';
import {Toaster} from 'sonner';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "FrontedPracticasWipay",
  description: "Generated by Pablo García Melero",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-black dark:text-white`}>
        <ThemeProvider>
          {/*<ThemeToggleButton />*/}
          <ReactQueryProvider>
            <SidebarProvider>
              <LayoutWithSidebar>
                <PageTransitionWrapper>
                    {children}
                </PageTransitionWrapper>
                </LayoutWithSidebar>
            </SidebarProvider>
          </ReactQueryProvider>
          <Toaster
            richColors
            position="top-right"
            duration={3000}
            closeButton
          />
        </ThemeProvider>
      </body>
    </html>
  );
}